/* Observable page DOM and same-origin fetch boundary; not a real browser. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const script = fs.readFileSync(process.argv[2], 'utf8');
function element() {
  return {textContent:'', hidden:false, disabled:false, value:'', checked:false, children:[], listeners:{},
    append(...nodes){this.children.push(...nodes);}, replaceChildren(...nodes){this.children=nodes;},
    addEventListener(name, callback){this.listeners[name]=callback;}, setAttribute(name,value){this[name]=value;}};
}
function openPage() {
  const elements={}, requests=[], timers=[];
  const clock={now:10000};
  const context={document:{getElementById(id){return elements[id] ||= element();},createElement:element},
    fetch(path,options={}){return new Promise((resolve,reject)=>requests.push({path,options,resolve,reject}));},
    setInterval(callback){timers.push(callback);}, Date:{now:()=>clock.now}, confirm:()=>true};
  vm.runInNewContext(script,context);
  return {elements,requests,clock,tick:()=>timers.forEach(callback=>callback())};
}
const config={channel:157,radio_txpower_dbm:12,downlink_mcs:3,uplink_mcs:6,uftp_rate_kbps:15000};
const bounds={downlink_mcs:3,min_rate_kbps:11000,max_rate_kbps:19000,default_rate_kbps:16000};
const snapshot={instance_id:'server-one',state_version:4,generated_at:'now',
  server:{state:'idle',tun:{is_active:true},link_process:{running:true},start_blockers:[]},
  job:null,current_job:null,recovery_state:'not_required',nodes:[],events:[]};
const initial={config,rate_bounds:{'3':bounds,'6':{...bounds,downlink_mcs:6,min_rate_kbps:33000,max_rate_kbps:46000,default_rate_kbps:39000}},snapshot};
async function flush(){for(let i=0;i<20;i++) await Promise.resolve();}
async function reply(request,body,status=200){request.resolve({ok:status<400,status,json:async()=>body});await flush();}
const click=(page,id)=>page.elements[id].listeners.click();
const submit=page=>page.elements['radio-form'].listeners.submit({preventDefault(){}});
(async()=>{
  const page=openPage();
  assert.equal(page.requests[0].path,'/api/v1/radio/config');
  assert.equal(page.requests[0].options.cache,'no-store');
  await reply(page.requests[0],initial);
  assert.equal(page.elements.channel.value,'157');
  assert.match(page.elements['current-config'].textContent,/157.*12.*3.*6.*15000/);
  assert.match(page.elements['rate-range'].textContent,/11000.*19000.*16000/);
  assert.equal(page.elements.apply.disabled,true,'validation does not apply implicitly');
  assert.equal(page.elements.validate.disabled,false);
  const confirmation={token:'checked-token',instance_id:'server-one',state_version:4,expires_in_seconds:30};
  const validated={config,rate_bounds:bounds,warning:null,confirmation};
  function edit(page,id,value) {page.elements[id].value=String(value);page.elements[id].listeners.input();}
  let pending=submit(page);
  assert.equal(page.requests[1].path,'/api/v1/radio/config/validate');
  assert.deepEqual(JSON.parse(page.requests[1].options.body),{config});
  assert.equal(page.requests[1].options.headers['Content-Type'],'application/json');
  await reply(page.requests[1],validated);await pending;
  assert.match(page.elements['validated-config'].textContent,/157.*15000/);
  assert.equal(page.elements.apply.disabled,false);
  assert.equal(page.requests.length,2,'validation never auto-applies');
  edit(page,'uftp_rate_kbps',20000);
  assert.equal(page.elements.apply.disabled,true,'editing clears confirmation');
  assert.equal(page.elements['confirm-risk'].checked,false);
  assert.match(page.elements['rate-warning'].textContent,/安全范围/);
  pending=submit(page);
  await reply(page.requests[2],{...validated,config:{...config,uftp_rate_kbps:20000},warning:'越界：可能造成丢包'});await pending;
  assert.equal(page.elements.apply.disabled,true,'risk requires explicit checkbox');
  assert.match(page.elements['rate-warning'].textContent,/越界：可能造成丢包/);
  await click(page,'apply');
  assert.equal(page.requests.length,3,'disabled operation also guards handlers');
  page.elements['confirm-risk'].checked=true;
  page.elements['confirm-risk'].listeners.change();
  assert.equal(page.elements.apply.disabled,false);
  pending=click(page,'apply');
  assert.equal(page.requests[3].path,'/api/v1/radio/config/apply');
  assert.deepEqual(JSON.parse(page.requests[3].options.body),{confirmation_token:'checked-token',confirm_risk:true});
  await click(page,'apply');
  assert.equal(page.requests.length,4,'double apply is blocked');
  await reply(page.requests[3],{status:'completed',effective_config:{...config,uftp_rate_kbps:20000}});
  await reply(page.requests[4],initial);await pending;
  assert.match(page.elements['action-status'].textContent,/completed/);
  assert.equal(page.elements.apply.disabled,true,'confirmation is single-use');
  edit(page,'downlink_mcs',6);
  assert.match(page.elements['rate-range'].textContent,/33000.*46000.*39000/);
  edit(page,'downlink_mcs',3);edit(page,'uftp_rate_kbps',15000);
  pending=submit(page);await reply(page.requests[5],validated);await pending;
  page.clock.now+=31000;page.tick();await flush();
  assert.equal(page.elements.apply.disabled,true,'expired confirmation is unusable');
  await reply(page.requests[6],initial);
  pending=submit(page);
  edit(page,'channel',153);
  await reply(page.requests[7],validated);await pending;
  assert.equal(page.elements.apply.disabled,true,'late validation cannot restore an edited confirmation');
  edit(page,'channel',161);
  await submit(page);
  assert.equal(page.requests.length,8,'forbidden channel rejected before validation');
  assert.match(page.elements['action-error'].textContent,/161/);
  edit(page,'channel',157);
  pending=submit(page);
  await reply(page.requests[8],{error:{code:'INVALID_RADIO_CONFIG',message:'非法组合'}},400);await pending;
  assert.match(page.elements['action-error'].textContent,/INVALID_RADIO_CONFIG.*非法组合/);
  pending=submit(page);await reply(page.requests[9],validated);await pending;
  let refresh=click(page,'refresh');
  await reply(page.requests[10],{...initial,snapshot:{...snapshot,state_version:5}});await refresh;
  assert.equal(page.elements.apply.disabled,true,'state version invalidates validation');
  refresh=click(page,'refresh');
  const active={job_id:'job-1',execution_result:'running',recovery_state:'not_required'};
  const running={...snapshot,state_version:6,server:{...snapshot.server,state:'running'},job:active,current_job:active};
  await reply(page.requests[11],{...initial,snapshot:running});await refresh;
  assert.equal(page.elements.validate.disabled,true);
  assert.equal(page.elements.apply.disabled,true);
  assert.equal(page.elements['emergency-stop'].disabled,false);
  assert.match(page.elements['apply-blockers'].textContent,/运行|待命/);
  await submit(page);
  assert.equal(page.requests.length,12,'running cluster cannot validate or apply');
  pending=click(page,'emergency-stop');
  assert.equal(page.requests[12].path,'/api/v1/jobs/job-1/abort');
  assert.deepEqual(JSON.parse(page.requests[12].options.body),{reason:'operator_abort'});
  await reply(page.requests[12],{accepted:true});
  assert.match(page.elements['stop-status'].textContent,/已受理.*资源/);
  const blocked={...snapshot,state_version:7,job:{...active,execution_result:'aborted',recovery_state:'blocked'},recovery_state:'blocked'};
  await reply(page.requests[13],{...initial,snapshot:blocked});await pending;
  assert.equal(page.elements.apply.disabled,true);
  assert.equal(page.elements.validate.disabled,true);
  assert.match(page.elements['recovery-state'].textContent,/恢复受阻/);
  refresh=click(page,'refresh');page.requests[14].reject(new Error('offline'));await refresh;
  assert.match(page.elements['connection-error'].textContent,/过时.*offline/);
  assert.equal(page.elements.validate.disabled,true);
  refresh=click(page,'refresh');await reply(page.requests[15],initial);await refresh;
  assert.equal(page.elements.validate.disabled,false);
  assert.equal(page.elements['connection-error'].hidden,true);
  assert.equal(page.elements.channel.value,'157','polling preserves edited fields');
  pending=submit(page);await reply(page.requests[16],validated);await pending;
  pending=click(page,'apply');
  await reply(page.requests[17],{error:{code:'RADIO_CONFIRMATION_STALE',message:'请重新校验'}},409);await pending;
  assert.match(page.elements['action-error'].textContent,/RADIO_CONFIRMATION_STALE.*请重新校验/);
  assert.equal(page.elements.apply.disabled,true);
  refresh=click(page,'refresh');await reply(page.requests[18],initial);await refresh;
  pending=submit(page);await reply(page.requests[19],validated);await pending;
  refresh=click(page,'refresh');page.requests[20].reject(new Error('offline'));await refresh;
  assert.equal(page.elements.apply.disabled,true,'disconnect discards confirmation');
  refresh=click(page,'refresh');
  await reply(page.requests[21],{...initial,snapshot:{...snapshot,instance_id:'server-two'}});await refresh;
  assert.match(page.elements['instance-notice'].textContent,/重启/);
  assert.equal(page.elements.apply.disabled,true,'reconnect never restores a confirmation');
  const empty=openPage();await reply(empty.requests[0],{...initial,config:null});
  assert.match(empty.elements['current-config'].textContent,/未确认/);
  const race=openPage();
  const newer=click(race,'refresh');await reply(race.requests[1],initial);await newer;
  await reply(race.requests[0],{...initial,config:null,snapshot:{...snapshot,instance_id:'obsolete'}});
  assert.match(race.elements['current-config'].textContent,/157/,'older response cannot replace newer state');
  const failed=openPage();await reply(failed.requests[0],initial);
  pending=submit(failed);await reply(failed.requests[1],validated);await pending;
  pending=click(failed,'apply');
  await reply(failed.requests[2],{status:'radio_error',failed_phase:'confirmed',unresponsive_nodes:[2],error_message:'最终确认失败'});
  await reply(failed.requests[3],{...initial,config:null,snapshot:{...snapshot,state_version:8,server:{...snapshot.server,state:'radio_error'}}});await pending;
  assert.match(failed.elements['action-status'].textContent,/radio_error.*最终确认失败/);
  assert.match(failed.elements['transaction-result'].textContent,/confirmed/);
  assert.match(failed.elements['server-state'].textContent,/RADIO_ERROR/);
  assert.equal(failed.elements.apply.disabled,true);
  assert.equal(failed.elements.validate.disabled,true);
  const automatic=click(failed,'refresh');failed.requests[4].reject(new Error('lost'));await automatic;
  failed.clock.now+=3000;failed.tick();await flush();
  await reply(failed.requests[5],initial);
  assert.equal(failed.elements['connection-error'].hidden,true,'polling restores authoritative state');
  assert.equal(failed.elements.validate.disabled,false);
  assert.equal(failed.elements.apply.disabled,true);
  const pendingRead=click(failed,'refresh');
  pending=submit(failed);
  await reply(failed.requests[7],validated);await pending;
  await reply(failed.requests[6],{...initial,snapshot:{...snapshot,state_version:99}});await pendingRead;
  assert.equal(failed.elements.apply.disabled,false,'pre-validation read cannot discard newer confirmation');
  edit(failed,'channel',153);
  const readAfterEdit=click(failed,'refresh');await reply(failed.requests[8],initial);await readAfterEdit;
  assert.equal(failed.elements.channel.value,'153','polling does not overwrite unsaved edits');
  const earlyEdit=openPage();
  edit(earlyEdit,'channel',153);
  await reply(earlyEdit.requests[0],initial);
  assert.equal(earlyEdit.elements.channel.value,'153','initial read must preserve input changed while loading');
  console.log('Radio page Node VM: configuration, validation, risk, expiry, conflicts, abort and recovery passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
